# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75296d3386503ac5d1632177a7919e985a9d90c38bddfaadc63c38697e14b8b0786e0b9908279dd5d4e1a35a8f741a465488733908b0f894ac79fc3a75226c8d
  five_consumer_key: <%= ENV["MYFIVEHUNDRED_CONSUMER_KEY"] %>

test:
  secret_key_base: 84e14dc9087faa4b797539e848c0cb1ef565aa48ac4cfbc3323fc326ba83da2c155ca74c31ef845f4344c52a6d17f6aed301dc1edc5779bd16dcdf0af32efb21
  five_consumer_key: <%= ENV["MYFIVEHUNDRED_CONSUMER_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  five_consumer_key: <%= ENV["MYFIVEHUNDRED_CONSUMER_KEY"] %>
